## Data Wrangling
The goal is to unify all datasets, filter relevant features, enrich data.

In [1]:
import pandas as pd 
import pycountry

### Read Data
Dataset: World Happiness 2015 to 2022

Collected from [Kaggle](https://www.kaggle.com/datasets/mathurinache/world-happiness-report?select=2022.csv)

Features of interest: real GDP per capita, social support, healthy life expectancy, freedom to make life choices, generosity, perceptions of corruption

In [2]:
df_2015 = pd.read_csv('../data/raw/HappinessScore2015.csv')
df_2016 = pd.read_csv('../data/raw/HappinessScore2016.csv')
df_2017 = pd.read_csv('../data/raw/HappinessScore2017.csv')
df_2018 = pd.read_csv('../data/raw/HappinessScore2018.csv')
df_2019 = pd.read_csv('../data/raw/HappinessScore2019.csv')
df_2020 = pd.read_csv('../data/raw/HappinessScore2020.csv')
df_2021 = pd.read_csv('../data/raw/HappinessScore2021.csv')
df_2022 = pd.read_csv('../data/raw/HappinessScore2022.csv')

### Wrangle Data

##### Explore Data

In [3]:
# Explore Data
print(2015, len(df_2015), sorted(list(df_2015.columns)))
print(2016, len(df_2016), sorted(list(df_2016.columns)))
print(2017, len(df_2017), sorted(list(df_2017.columns)))
print(2018, len(df_2018), sorted(list(df_2018.columns)))
print(2019, len(df_2019), sorted(list(df_2019.columns)))
print(2020, len(df_2020), sorted(list(df_2020.columns)))
print(2021, len(df_2021), sorted(list(df_2021.columns)))
print(2022, len(df_2022), sorted(list(df_2022.columns)))

2015 158 ['Country', 'Dystopia Residual', 'Economy (GDP per Capita)', 'Family', 'Freedom', 'Generosity', 'Happiness Rank', 'Happiness Score', 'Health (Life Expectancy)', 'Region', 'Standard Error', 'Trust (Government Corruption)']
2016 157 ['Country', 'Dystopia Residual', 'Economy (GDP per Capita)', 'Family', 'Freedom', 'Generosity', 'Happiness Rank', 'Happiness Score', 'Health (Life Expectancy)', 'Lower Confidence Interval', 'Region', 'Trust (Government Corruption)', 'Upper Confidence Interval']
2017 155 ['Country', 'Dystopia.Residual', 'Economy..GDP.per.Capita.', 'Family', 'Freedom', 'Generosity', 'Happiness.Rank', 'Happiness.Score', 'Health..Life.Expectancy.', 'Trust..Government.Corruption.', 'Whisker.high', 'Whisker.low']
2018 156 ['Country or region', 'Freedom to make life choices', 'GDP per capita', 'Generosity', 'Healthy life expectancy', 'Overall rank', 'Perceptions of corruption', 'Score', 'Social support']
2019 156 ['Country or region', 'Freedom to make life choices', 'GDP per capita', 'Generosity', 'Healthy life expectancy', 'Overall rank', 'Perceptions of corruption', 'Score', 'Social support']
2020 153 ['Country name', 'Dystopia + residual', 'Explained by: Freedom to make life choices', 'Explained by: Generosity', 'Explained by: Healthy life expectancy', 'Explained by: Log GDP per capita', 'Explained by: Perceptions of corruption', 'Explained by: Social support', 'Freedom to make life choices', 'Generosity', 'Healthy life expectancy', 'Ladder score', 'Ladder score in Dystopia', 'Logged GDP per capita', 'Perceptions of corruption', 'Regional indicator', 'Social support', 'Standard error of ladder score', 'lowerwhisker', 'upperwhisker']
2021 149 ['Country name', 'Dystopia + residual', 'Explained by: Freedom to make life choices', 'Explained by: Generosity', 'Explained by: Healthy life expectancy', 'Explained by: Log GDP per capita', 'Explained by: Perceptions of corruption', 'Explained by: Social support', 'Freedom to make life choices', 'Generosity', 'Healthy life expectancy', 'Ladder score', 'Ladder score in Dystopia', 'Logged GDP per capita', 'Perceptions of corruption', 'Regional indicator', 'Social support', 'Standard error of ladder score', 'lowerwhisker', 'upperwhisker']
2022 147 ['Country', 'Dystopia (1.83) + residual', 'Explained by: Freedom to make life choices', 'Explained by: GDP per capita', 'Explained by: Generosity', 'Explained by: Healthy life expectancy', 'Explained by: Perceptions of corruption', 'Explained by: Social support', 'Happiness score', 'RANK', 'Whisker-high', 'Whisker-low']

In [4]:
# View datasets to get an overall picture
df_2015.head(3)

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204

In [5]:
df_2019.head(3)

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,3,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341

In [6]:
df_2020.head(3)

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,Western Europe,7.8087,0.031156,7.869766,7.747634,10.639267,0.954330,71.900825,0.949172,-0.059482,0.195445,1.972317,1.285190,1.499526,0.961271,0.662317,0.159670,0.477857,2.762835
1,Denmark,Western Europe,7.6456,0.033492,7.711245,7.579955,10.774001,0.955991,72.402504,0.951444,0.066202,0.168489,1.972317,1.326949,1.503449,0.979333,0.665040,0.242793,0.495260,2.432741
2,Switzerland,Western Europe,7.5599,0.035014,7.628528,7.491272,10.979933,0.942847,74.102448,0.921337,0.105911,0.303728,1.972317,1.390774,1.472403,1.040533,0.628954,0.269056,0.407946,2.350267

In [7]:
df_2022.head(3)

,RANK,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.83) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,1,Finland,"7,821","7,886","7,756","2,518","1,892","1,258","0,775","0,736","0,109","0,534"
1,2,Denmark,"7,636","7,710","7,563","2,226","1,953","1,243","0,777","0,719","0,188","0,532"
2,3,Iceland,"7,557","7,651","7,464","2,320","1,936","1,320","0,803","0,718","0,270","0,191"

In [8]:
# Understand 'Overall rank', 'Score', 'Happiness Score', 'Dystopia Residual' 
print(list(df_2017['Dystopia.Residual'])[:10])
print(list(df_2017['Happiness.Rank'])[:10])
print(list(df_2017['Happiness.Score'])[:10])
print(list(df_2018['Overall rank'])[:10])
print(list(df_2018['Score'])[:10])
print(list(df_2021['Ladder score in Dystopia'].unique())[:10])

[2.27702665328979, 2.31370735168457, 2.32271528244019, 2.2767162322998, 2.4301815032959, 2.29480409622192, 2.18726444244385, 2.0464563369751, 2.09753799438477, 2.06521081924438]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[7.53700017929077, 7.52199983596802, 7.50400018692017, 7.49399995803833, 7.4689998626709, 7.3769998550415, 7.31599998474121, 7.31400012969971, 7.28399991989136, 7.28399991989136]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[7.632, 7.594, 7.555, 7.495, 7.487, 7.441, 7.328, 7.324, 7.314, 7.272]
[2.43]

*Remarks*
- Relationship between datasets:
    - It seems that from 2020 the columns 'Explained by...' are the ones equivalent to the previous datasets. 
    - Happiness Score = Score = Ladder Score. 
    - Happiness Rank = Overall Rank.
- From 2020 to 2021 there are no records of 'Happiness Rank'. Add it manually.
- From 2015 to 2017 there are no entries for 'Social Support', it will be interpolated.
- From 2018 to 2019 there are no entries for 'Dystopia Residual', it will be interpolated.

##### Organize and Clean Data

In [9]:
# Add rank to 2020 & 2021.The records are already sorted by happiness
df_2020['Happiness Rank'] = df_2020.index + 1
df_2021['Happiness Rank'] = df_2021.index + 1

# Avoid future repeated columns when renaming
df_2020 = df_2020.drop(['Generosity', 'Perceptions of corruption', 'Social support'], axis=1)
df_2021 = df_2021.drop(['Generosity', 'Perceptions of corruption', 'Social support'], axis=1)

In [10]:
# 2015 ['Country', 'Dystopia Residual', 'Economy (GDP per Capita)', 'Family', 'Freedom', 'Generosity', 'Happiness Rank', 'Happiness Score', 'Health (Life Expectancy)', 'Region', 'Standard Error', 'Trust (Government Corruption)']
# 2016 ['Country', 'Dystopia Residual', 'Economy (GDP per Capita)', 'Family', 'Freedom', 'Generosity', 'Happiness Rank', 'Happiness Score', 'Health (Life Expectancy)', 'Lower Confidence Interval', 'Region', 'Trust (Government Corruption)', 'Upper Confidence Interval']
# 2017 ['Country', 'Dystopia.Residual', 'Economy..GDP.per.Capita.', 'Family', 'Freedom', 'Generosity', 'Happiness.Rank', 'Happiness.Score', 'Health..Life.Expectancy.', 'Trust..Government.Corruption.', 'Whisker.high', 'Whisker.low']
# 2018 ['Country or region', 'Freedom to make life choices', 'GDP per capita', 'Generosity', 'Healthy life expectancy', 'Overall rank', 'Perceptions of corruption', 'Score', 'Social support']
# 2019 ['Country or region', 'Freedom to make life choices', 'GDP per capita', 'Generosity', 'Healthy life expectancy', 'Overall rank', 'Perceptions of corruption', 'Score', 'Social support']
# 2020 ['Country name', 'Dystopia + residual', 'Explained by: Freedom to make life choices', 'Explained by: Generosity', 'Explained by: Healthy life expectancy', 'Explained by: Log GDP per capita', 'Explained by: Perceptions of corruption', 'Explained by: Social support', 'Freedom to make life choices', 'Generosity', 'Healthy life expectancy', 'Ladder score', 'Ladder score in Dystopia', 'Logged GDP per capita', 'Perceptions of corruption', 'Regional indicator', 'Social support', 'Standard error of ladder score', 'lowerwhisker', 'upperwhisker']
# 2021 ['Country name', 'Dystopia + residual', 'Explained by: Freedom to make life choices', 'Explained by: Generosity', 'Explained by: Healthy life expectancy', 'Explained by: Log GDP per capita', 'Explained by: Perceptions of corruption', 'Explained by: Social support', 'Freedom to make life choices', 'Generosity', 'Healthy life expectancy', 'Ladder score', 'Ladder score in Dystopia', 'Logged GDP per capita', 'Perceptions of corruption', 'Regional indicator', 'Social support', 'Standard error of ladder score', 'lowerwhisker', 'upperwhisker']
# 2022 ['Country', 'Dystopia (1.83) + residual', 'Explained by: Freedom to make life choices', 'Explained by: GDP per capita', 'Explained by: Generosity', 'Explained by: Healthy life expectancy', 'Explained by: Perceptions of corruption', 'Explained by: Social support', 'Happiness score', 'RANK', 'Whisker-high', 'Whisker-low']

# Features of interest: GDP per capita, social support, healthy life expectancy, freedom to make life choices, generosity, perceptions of corruption
# Country - Dystopia Residual - GPD per Capita - Freedom - Generosity - Healthy life expectancy - Perceptions of corruption - Social support - Happiness Rank
df_2015r = df_2015.rename(columns= {'Economy (GDP per Capita)': 'GDP per capita', 'Health (Life Expectancy)': 'Healthy life expectancy', 'Trust (Government Corruption)': 'Perceptions of corruption'})
df_2016r = df_2016.rename(columns= {'Economy (GDP per Capita)': 'GDP per capita', 'Health (Life Expectancy)': 'Healthy life expectancy', 'Trust (Government Corruption)': 'Perceptions of corruption'})
df_2017r = df_2017.rename(columns= {'Dystopia.Residual': 'Dystopia Residual', 'Economy..GDP.per.Capita.': 'GDP per capita', 'Health..Life.Expectancy.': 'Healthy life expectancy', 'Trust..Government.Corruption.': 'Perceptions of corruption', 'Happiness.Rank': 'Happiness Rank'})
df_2018r = df_2018.rename(columns= {'Country or region': 'Country', 'Freedom to make life choices': 'Freedom', 'Overall rank': 'Happiness Rank'})
df_2019r = df_2019.rename(columns= {'Country or region': 'Country', 'Freedom to make life choices': 'Freedom', 'Overall rank': 'Happiness Rank'})
df_2020r = df_2020.rename(columns= {'Country name': 'Country', 'Dystopia + residual': 'Dystopia Residual', 'Explained by: Log GDP per capita': 'GDP per capita', 'Explained by: Freedom to make life choices':'Freedom',  'Explained by: Generosity': 'Generosity', 'Explained by: Perceptions of corruption': 'Perceptions of corruption', 'Explained by: Social support': 'Social support'})
df_2021r = df_2021.rename(columns= {'Country name': 'Country', 'Dystopia + residual': 'Dystopia Residual', 'Explained by: Log GDP per capita': 'GDP per capita', 'Explained by: Freedom to make life choices':'Freedom', 'Explained by: Generosity': 'Generosity', 'Explained by: Perceptions of corruption': 'Perceptions of corruption', 'Explained by: Social support': 'Social support'})
df_2022r = df_2022.rename(columns= {'Dystopia (1.83) + residual': 'Dystopia Residual', 'Explained by: GDP per capita': 'GDP per capita', 'Explained by: Freedom to make life choices':'Freedom', 'Explained by: Generosity': 'Generosity', 'Explained by: Healthy life expectancy': 'Healthy life expectancy', 'Explained by: Perceptions of corruption': 'Perceptions of corruption', 'Explained by: Social support': 'Social support', 'RANK': 'Happiness Rank'})

##### Add Features

In [11]:
# Add year to all datasets
df_2015r['Year']= 2015
df_2016r['Year']= 2016
df_2017r['Year']= 2017
df_2018r['Year']= 2018
df_2019r['Year']= 2019
df_2020r['Year']= 2020
df_2021r['Year']= 2021
df_2022r['Year']= 2022

##### Extract relevant features

In [12]:
# Country: Name of the country
# Happiness Rank:Rank of the country based on the Happiness Score 
# Happiness Score: A metric measured in 2016 by asking the sampled people the question: "How would you rate your happiness on a scale of 0 to 10 where 10 is the happiest" 
# Whisker High: Lower Confidence Interval of the Happiness Score 
# Whisker Low: Upper Confidence Interval of the Happiness Score 
# Economy (GDP per Capita): The extent to which GDP contributes to the calculation of the Happiness Score 
# Family: The extent to which Family contributes to the calculation of the Happiness Score 
# Health (Life Expectancy): The extent to which Life expectancy contributed to the calculation of the Happiness Score 
# Freedom: The extent to which Freedom contributed to the calculation of the Happiness Score 
# Trust (Government Corruption): The extent to which Perception of Corruption contributes to Happiness Score 
# Generosity: The extent to which Generosity contributed to the calculation of the Happiness Score 
# Dystopia Residual: The extent to which Dystopia Residual contributed to the calculation of the Happiness Score

# Check common columns accross datasets: Country - Dystopia Residual* - GPD per Capita - Freedom - Generosity - Healthy life expectancy - Perceptions of corruption - Social support* - Happiness Rank - Year
common_features = list(set(df_2015r.columns) & set(df_2016r.columns) & set(df_2017r.columns) & set(df_2018r.columns) & set(df_2019r.columns) & set(df_2020r.columns) & set(df_2021r.columns) & set(df_2022r.columns))
common_features

['Freedom',
 'Year',
 'Happiness Rank',
 'Generosity',
 'Healthy life expectancy',
 'Country',
 'Perceptions of corruption',
 'GDP per capita']

In [13]:
# Extract relevant features by filtering columns of interest
df_2015f = df_2015r[common_features + ['Dystopia Residual']]
df_2016f = df_2016r[common_features + ['Dystopia Residual']]
df_2017f = df_2017r[common_features + ['Dystopia Residual']]
df_2018f = df_2018r[common_features + ['Social support']]
df_2019f = df_2019r[common_features + ['Social support']]
df_2020f = df_2020r[common_features + ['Social support', 'Dystopia Residual']]
df_2021f = df_2021r[common_features + ['Social support', 'Dystopia Residual']]
df_2022f = df_2022r[common_features + ['Social support', 'Dystopia Residual']]

In [14]:
# merge df concating rows, keeping all columns and having nan where the column does not exist
df = pd.concat([df_2015f, df_2016f, df_2017f, df_2018f, df_2019f, df_2020f, df_2021f, df_2022f] ,    # Combine vertically
                          ignore_index = True,
                          sort = False)
df

,Freedom,Year,Happiness Rank,Generosity,Healthy life expectancy,Country,Perceptions of corruption,GDP per capita,Dystopia Residual,Social support
0,0.66557,2015,1,0.29678,0.94143,Switzerland,0.41978,1.39651,2.51738,NaN
1,0.62877,2015,2,0.4363,0.94784,Iceland,0.14145,1.30232,2.70201,NaN
2,0.64938,2015,3,0.34139,0.87464,Denmark,0.48357,1.32548,2.49204,NaN
3,0.66973,2015,4,0.34699,0.88521,Norway,0.36503,1.459,2.46531,NaN
4,0.63297,2015,5,0.45811,0.90563,Canada,0.32957,1.32629,2.45176,NaN
...,...,...,...,...,...,...,...,...,...,...
1226,"0,621",2022,143,"0,187","0,462",Rwanda*,"0,544","0,785","0,536","0,133"
1227,"0,329",2022,144,"0,106","0,270",Zimbabwe,"0,105","0,947","0,548","0,690"
1228,"0,103",2022,145,"0,082","0,631",Lebanon,"0,034","1,392","0,216","0,498"
1229,"0,000",2022,146,"0,089","0,289",Afghanistan,"0,005","0,758","1,263","0,000"
1230,NaN,2022,147,NaN,NaN,xx,NaN,NaN,NaN,NaN

##### Clean Dataset

Validate Country names

In [15]:
# Validate countries in dataset
world_countries = [country.name for country in list(pycountry.countries)]

print(list(df[~df.Country.isin(world_countries)].Year.value_counts()))  # which datasets are the problem
print(set(df[~df.Country.isin(world_countries)].Country))  # the library does not do a great job, but now is easier to filter by eye

[35, 21, 20, 20, 20, 20, 19, 18]
{'Chad*', 'Iran', 'Liberia*', 'Libya*', 'Macedonia', 'Mauritania*', 'Luxembourg*', 'Gambia*', 'South Korea', 'Bolivia', 'Turkmenistan*', 'Congo (Brazzaville)', 'Syria', 'Ivory Coast', 'Madagascar*', 'Eswatini, Kingdom of*', 'Comoros*', 'Russia', 'Tanzania', 'Moldova', 'Botswana*', 'Azerbaijan*', 'Northern Cyprus', 'Czech Republic', 'Niger*', 'Taiwan', 'Taiwan Province of China', 'Trinidad & Tobago', 'Rwanda*', 'Somaliland region', 'Somaliland Region', 'Palestinian Territories*', 'Congo (Kinshasa)', 'North Cyprus*', 'Swaziland', 'Kuwait*', 'Kosovo', 'Laos', 'North Cyprus', 'xx', 'Vietnam', 'Yemen*', 'Lesotho*', 'Venezuela', 'Hong Kong S.A.R., China', 'Guatemala*', 'Hong Kong S.A.R. of China', 'Belarus*', 'Palestinian Territories'}

In [16]:
# remove * from countries' names
df['Country'] = df['Country'].str.replace('*', '')

print(list(df[~df.Country.isin(world_countries)].Year.value_counts()))  # which datasets are the problem
print(set(df[~df.Country.isin(world_countries)].Country))

[21, 20, 20, 20, 20, 19, 18, 17]
{'Iran', 'Macedonia', 'South Korea', 'Bolivia', 'Congo (Brazzaville)', 'Syria', 'Ivory Coast', 'Russia', 'Tanzania', 'Moldova', 'Eswatini, Kingdom of', 'Northern Cyprus', 'Czech Republic', 'Taiwan', 'Taiwan Province of China', 'Trinidad & Tobago', 'Somaliland region', 'Somaliland Region', 'Congo (Kinshasa)', 'Swaziland', 'Kosovo', 'Laos', 'North Cyprus', 'xx', 'Vietnam', 'Venezuela', 'Hong Kong S.A.R., China', 'Hong Kong S.A.R. of China', 'Palestinian Territories'}

/tmp/ipykernel_4595/466095391.py:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['Country'] = df['Country'].str.replace('*', '')

In [17]:
# review across datasets: Congo, China, Cyprus, Somaliland Region, Swaziland & Taiwan & Hong Kong Province of China to Taiwan

print('Congo appearances\n', df[df['Country'].str.contains('Congo')].Country) # Version of Congo, need to update Congo to Kinshasa
print('\nChina appearances\n', df[df['Country'].str.contains('China')].Country) # Version of China
print('\nHong Kong appearances\n', df[df['Country'].str.contains('Hong Kong')].Country) # Version of Hong Kong
print('\nCyprus appearances\n', df[df['Country'].str.contains('Cyprus')].Country) # There are two variants Northen Cyprus and North Cyprus
print('\nEswatini appearances\n', df[df['Country'].str.contains('Eswatini')].Country) # Eswatini and formerly named , update name if it is updated in the rest
print('\nSwaziland appearances\n', df[df['Country'].str.contains('Swaziland')].Country) # Eswatini and formerly named Swaziland, update name if it is updated in the rest
print('\nSomaliland appearances\n', df[df['Country'].str.contains('Somaliland')].Country) # Only one variant so it is ok

Congo appearances
 119        Congo (Kinshasa)
138     Congo (Brazzaville)
282        Congo (Kinshasa)
284     Congo (Brazzaville)
438     Congo (Brazzaville)
440        Congo (Kinshasa)
583     Congo (Brazzaville)
601        Congo (Kinshasa)
728     Congo (Brazzaville)
752        Congo (Kinshasa)
869     Congo (Brazzaville)
912        Congo (Kinshasa)
1017    Congo (Brazzaville)
1182                  Congo
Name: Country, dtype: object

China appearances
 83                          China
240                         China
347      Taiwan Province of China
385       Hong Kong S.A.R., China
393                         China
555                         China
718                         China
806      Taiwan Province of China
859     Hong Kong S.A.R. of China
875                         China
958      Taiwan Province of China
1011    Hong Kong S.A.R. of China
1018                        China
1109     Taiwan Province of China
1155                        China
1164    Hong Kong S.A.R. of China
Name: Country, dtype: object

Hong Kong appearances
 71                      Hong Kong
232                     Hong Kong
385       Hong Kong S.A.R., China
545                     Hong Kong
701                     Hong Kong
859     Hong Kong S.A.R. of China
1011    Hong Kong S.A.R. of China
1164    Hong Kong S.A.R. of China
Name: Country, dtype: object

Cyprus appearances
 65         North Cyprus
66               Cyprus
219        North Cyprus
226              Cyprus
375        North Cyprus
379              Cyprus
527     Northern Cyprus
530              Cyprus
674              Cyprus
689     Northern Cyprus
826              Cyprus
857        North Cyprus
973              Cyprus
1008       North Cyprus
1124             Cyprus
1162       North Cyprus
Name: Country, dtype: object

Eswatini appearances
 1208    Eswatini, Kingdom of
Name: Country, dtype: object

Swaziland appearances
 100     Swaziland
760     Swaziland
913     Swaziland
1064    Swaziland
Name: Country, dtype: object

Somaliland appearances
 90     Somaliland region
254    Somaliland Region
Name: Country, dtype: object

In [18]:
# unify and fix errors in country names 
df = df.drop(df[df.Country == 'xx'].index)
df.loc[1182, 'Country'] = 'Congo (Kinshasa)'
df.loc[347, 'Country'] = 'Taiwan'
df.loc[df.Country == 'Swaziland', 'Country'] = 'Eswatini, Kingdom of'
df.loc[df.Country == 'Northern Cyprus', 'Country'] = 'North Cyprus'
df.loc[[385, 859, 1011, 1164], 'Country'] = 'Hong Kong'

##### Validate Data Types

In [19]:
# check for datatypes
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1230 entries, 0 to 1229
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Freedom                    1230 non-null   object
 1   Year                       1230 non-null   int64
 2   Happiness Rank             1230 non-null   int64
 3   Generosity                 1230 non-null   object
 4   Healthy life expectancy    1230 non-null   object
 5   Country                    1230 non-null   object
 6   Perceptions of corruption  1229 non-null   object
 7   GDP per capita             1230 non-null   object
 8   Dystopia Residual          918 non-null    object
 9   Social support             760 non-null    object
dtypes: int64(2), object(8)
memory usage: 96.2+ KB

In [20]:
# transform to numeric
num_cols = df.drop(['Country'], axis=1).columns
df[num_cols] = df[num_cols].apply(pd.to_numeric, errors='coerce')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1230 entries, 0 to 1229
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Freedom                    1084 non-null   float64
 1   Year                       1230 non-null   int64
 2   Happiness Rank             1230 non-null   int64
 3   Generosity                 1084 non-null   float64
 4   Healthy life expectancy    1084 non-null   float64
 5   Country                    1230 non-null   object
 6   Perceptions of corruption  1083 non-null   float64
 7   GDP per capita             1084 non-null   float64
 8   Dystopia Residual          772 non-null    float64
 9   Social support             614 non-null    float64
dtypes: float64(7), int64(2), object(1)
memory usage: 96.2+ KB

In [21]:
df

,Freedom,Year,Happiness Rank,Generosity,Healthy life expectancy,Country,Perceptions of corruption,GDP per capita,Dystopia Residual,Social support
0,0.66557,2015,1,0.29678,0.94143,Switzerland,0.41978,1.39651,2.51738,NaN
1,0.62877,2015,2,0.43630,0.94784,Iceland,0.14145,1.30232,2.70201,NaN
2,0.64938,2015,3,0.34139,0.87464,Denmark,0.48357,1.32548,2.49204,NaN
3,0.66973,2015,4,0.34699,0.88521,Norway,0.36503,1.45900,2.46531,NaN
4,0.63297,2015,5,0.45811,0.90563,Canada,0.32957,1.32629,2.45176,NaN
...,...,...,...,...,...,...,...,...,...,...
1225,NaN,2022,142,NaN,NaN,Botswana,NaN,NaN,NaN,NaN
1226,NaN,2022,143,NaN,NaN,Rwanda,NaN,NaN,NaN,NaN
1227,NaN,2022,144,NaN,NaN,Zimbabwe,NaN,NaN,NaN,NaN
1228,NaN,2022,145,NaN,NaN,Lebanon,NaN,NaN,NaN,NaN
1229,NaN,2022,146,NaN,NaN,Afghanistan,NaN,NaN,NaN,NaN

##### Save Data

In [22]:
# Save processed data
df.to_csv('../data/processed/WorldHappinees2015_2022', index=False)